spring:
  application:
    name: paingan-eureka
  rabbitmq:
    host: localhost
    port: 5672
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    locator:
      discovery:
        enabled: true

server:
  port: ${server.port}
      
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
    
